# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Comment.create([
  { :content => "this is pretty awesome", :sound_id => 1, :user_id => 1, :created_at => "2013-06-09 20:16:12", :updated_at => "2013-06-09 20:16:12" },
  { :content => "that's spastic as hell", :sound_id => 1, :user_id => 1, :created_at => "2013-06-09 20:17:14", :updated_at => "2013-06-09 20:17:14" },
  { :content => "hihi hahaha", :sound_id => 1, :user_id => 1, :created_at => "2013-06-11 01:34:49", :updated_at => "2013-06-11 01:34:49" }
], :without_protection => true )



Image.create([
  { :name => "zoom", :description => "hihi", :url => nil, :created_at => "2013-06-09 20:12:41", :updated_at => "2013-06-09 20:12:41", :user_id => 1, :file_file_name => "code-girl_v-02-2-2-3d-wide-v-2c.jpeg", :file_content_type => "image/jpeg", :file_file_size => 1633372, :file_updated_at => "2013-06-09 20:12:40" },
  { :name => "Crazy car", :description => "Yup. It's a crazy car.", :url => nil, :created_at => "2013-06-12 18:10:47", :updated_at => "2013-06-12 18:10:47", :user_id => 1, :file_file_name => "8.jpg", :file_content_type => "image/jpeg", :file_file_size => 460857, :file_updated_at => "2013-06-12 18:10:47" },
  { :name => "\\m/", :description => "hell yeah", :url => nil, :created_at => "2013-06-12 18:12:18", :updated_at => "2013-06-12 18:12:18", :user_id => 1, :file_file_name => "2.jpg", :file_content_type => "image/jpeg", :file_file_size => 24635, :file_updated_at => "2013-06-12 18:12:18" },
  { :name => "Oh crap", :description => "", :url => nil, :created_at => "2013-06-12 18:17:25", :updated_at => "2013-06-12 18:17:25", :user_id => 2, :file_file_name => "3.jpg", :file_content_type => "image/jpeg", :file_file_size => 107356, :file_updated_at => "2013-06-12 18:17:24" },
  { :name => "Arrrr", :description => "", :url => nil, :created_at => "2013-06-12 18:17:49", :updated_at => "2013-06-12 18:17:49", :user_id => 2, :file_file_name => "5.jpg", :file_content_type => "image/jpeg", :file_file_size => 31269, :file_updated_at => "2013-06-12 18:17:48" },
  { :name => "inside my brain", :description => "", :url => nil, :created_at => "2013-06-12 18:19:52", :updated_at => "2013-06-12 18:19:52", :user_id => 3, :file_file_name => "1.jpg", :file_content_type => "image/jpeg", :file_file_size => 344582, :file_updated_at => "2013-06-12 18:19:52" },
  { :name => "crazy city", :description => "", :url => nil, :created_at => "2013-06-12 18:20:45", :updated_at => "2013-06-12 18:20:45", :user_id => 3, :file_file_name => "4.jpeg", :file_content_type => "image/jpeg", :file_file_size => 19606, :file_updated_at => "2013-06-12 18:20:44" },
  { :name => "hot girl 1", :description => "", :url => nil, :created_at => "2013-06-12 18:22:28", :updated_at => "2013-06-12 18:22:28", :user_id => 4, :file_file_name => "YZXx7ji.jpg", :file_content_type => "image/jpeg", :file_file_size => 306988, :file_updated_at => "2013-06-12 18:22:27" },
  { :name => "hot girl 2", :description => "", :url => nil, :created_at => "2013-06-12 18:22:43", :updated_at => "2013-06-12 18:22:43", :user_id => 4, :file_file_name => "louisecliffe.jpg", :file_content_type => "image/jpeg", :file_file_size => 129086, :file_updated_at => "2013-06-12 18:22:43" },
  { :name => "hot girl 3", :description => "", :url => nil, :created_at => "2013-06-12 18:22:59", :updated_at => "2013-06-12 18:22:59", :user_id => 4, :file_file_name => "melanieiglesias.jpg", :file_content_type => "image/jpeg", :file_file_size => 167992, :file_updated_at => "2013-06-12 18:22:59" },
  { :name => "hot girl 4", :description => "", :url => nil, :created_at => "2013-06-12 18:24:22", :updated_at => "2013-06-12 18:24:22", :user_id => 4, :file_file_name => "midori_beautiful_2.png", :file_content_type => "image/png", :file_file_size => 209440, :file_updated_at => "2013-06-12 18:24:21" }
], :without_protection => true )



Like.create([
  { :created_at => nil, :updated_at => nil, :user_id => nil, :sound_id => nil }
], :without_protection => true )



Relationship.create([
  { :follower_id => 4, :followed_id => 2, :created_at => "2013-06-12 18:25:46", :updated_at => "2013-06-12 18:25:46" },
  { :follower_id => 4, :followed_id => 3, :created_at => "2013-06-12 18:25:54", :updated_at => "2013-06-12 18:25:54" },
  { :follower_id => 2, :followed_id => 1, :created_at => "2013-06-12 18:26:26", :updated_at => "2013-06-12 18:26:26" },
  { :follower_id => 2, :followed_id => 4, :created_at => "2013-06-12 18:26:34", :updated_at => "2013-06-12 18:26:34" },
  { :follower_id => 2, :followed_id => 3, :created_at => "2013-06-12 18:26:57", :updated_at => "2013-06-12 18:26:57" },
  { :follower_id => 3, :followed_id => 4, :created_at => "2013-06-12 18:27:18", :updated_at => "2013-06-12 18:27:18" },
  { :follower_id => 3, :followed_id => 1, :created_at => "2013-06-12 18:27:25", :updated_at => "2013-06-12 18:27:25" },
  { :follower_id => 3, :followed_id => 2, :created_at => "2013-06-12 18:27:30", :updated_at => "2013-06-12 18:27:30" }
], :without_protection => true )



Sound.create([
  { :name => "zoom", :description => nil, :url => "/public/sound/zoomtest.mp3", :algorithm_name => nil, :created_at => "2013-06-09 20:12:44", :updated_at => "2013-06-09 20:12:44", :image_id => 1 },
  { :name => "Crazy car", :description => nil, :url => "/public/sound/Crazycartest.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:10:53", :updated_at => "2013-06-12 18:10:53", :image_id => 2 },
  { :name => "\\m/", :description => nil, :url => "/public/sound/_m_test.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:12:20", :updated_at => "2013-06-12 18:12:20", :image_id => 3 },
  { :name => "Oh crap", :description => nil, :url => "/public/sound/Ohcraptweety.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:17:27", :updated_at => "2013-06-12 18:17:27", :image_id => 4 },
  { :name => "Arrrr", :description => nil, :url => "/public/sound/Arrrrtweety.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:17:51", :updated_at => "2013-06-12 18:17:51", :image_id => 5 },
  { :name => "inside my brain", :description => nil, :url => "/public/sound/insidemybrainvoodoo.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:19:54", :updated_at => "2013-06-12 18:19:54", :image_id => 6 },
  { :name => "crazy city", :description => nil, :url => "/public/sound/crazycityvoodoo.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:20:47", :updated_at => "2013-06-12 18:20:47", :image_id => 7 },
  { :name => "hot girl 1", :description => nil, :url => "/public/sound/hotgirl1da_parrot.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:22:31", :updated_at => "2013-06-12 18:22:31", :image_id => 8 },
  { :name => "hot girl 2", :description => nil, :url => "/public/sound/hotgirl2da_parrot.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:22:46", :updated_at => "2013-06-12 18:22:46", :image_id => 9 },
  { :name => "hot girl 3", :description => nil, :url => "/public/sound/hotgirl3da_parrot.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:23:02", :updated_at => "2013-06-12 18:23:02", :image_id => 10 },
  { :name => "hot girl 4", :description => nil, :url => "/public/sound/hotgirl4da_parrot.mp3", :algorithm_name => nil, :created_at => "2013-06-12 18:24:24", :updated_at => "2013-06-12 18:24:24", :image_id => 11 }
], :without_protection => true )



User.create([
  { :username => "test", :password_hash => "sha1:1000:p+ypafBKDkJqp1v491Vl6p6aYEK1o2yn:ED7Va707QzxNBq0b+ofsDiFX2WogZprf\n", :email => "test@test.com", :full_name => "test", :created_at => "2013-06-09 20:12:11", :updated_at => "2013-06-09 20:12:11", :avatar_file_name => "photo1.jpg", :avatar_content_type => "image/jpeg", :avatar_file_size => 58651, :avatar_updated_at => "2013-06-09 20:12:11" },
  { :username => "tweety", :password_hash => "sha1:1000:VHZ8VFQCwQqSEzgcuS8vOuG28VNd9Py2:X4fphmIzwuMIF5D3Up73OnJXMZeA8M7y\n", :email => "a@a.com", :full_name => "Bob", :created_at => "2013-06-12 18:16:46", :updated_at => "2013-06-12 18:16:46", :avatar_file_name => "o3DIttT.jpg", :avatar_content_type => "image/jpeg", :avatar_file_size => 82926, :avatar_updated_at => "2013-06-12 18:16:46" },
  { :username => "voodoo", :password_hash => "sha1:1000:qYUR9c30FDJkYVQ82ZuArBj3QNgfax6q:uY/8g4NySci2nBSW+/dZb2QAp7sWdSZq\n", :email => "bizz@bazz.com", :full_name => "Bill O'Reilly", :created_at => "2013-06-12 18:19:34", :updated_at => "2013-06-12 18:19:34", :avatar_file_name => "1.jpg", :avatar_content_type => "image/jpeg", :avatar_file_size => 344582, :avatar_updated_at => "2013-06-12 18:19:34" },
  { :username => "da_parrot", :password_hash => "sha1:1000:uUlOnOQqwWbv7HzhXNewBmZD4fGYjdUF:Cy+Q2yD24HHnLr/lmEUDMIs7kHxqh/W7\n", :email => "floop@zoop.com", :full_name => "apple", :created_at => "2013-06-12 18:21:38", :updated_at => "2013-06-12 18:21:38", :avatar_file_name => "5.jpg", :avatar_content_type => "image/jpeg", :avatar_file_size => 31269, :avatar_updated_at => "2013-06-12 18:21:37" }
], :without_protection => true )


